# Generated by Django 2.2.14 on 2020-11-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_song', models.CharField(default='', max_length=255)),
                ('auth', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(default='', max_length=255)),
                ('song_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music_app.Song')),
            ],
        ),
    ]
