# Generated by Django 2.2.14 on 2020-11-19 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='play_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.PlayList'),
        ),
    ]
