# Generated by Django 2.2.14 on 2020-11-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20201119_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to='media/mp3/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='play_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.PlayList'),
        ),
    ]
