# Generated by Django 2.2.14 on 2020-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_auto_20201119_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_song',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image/'),
        ),
    ]
