# Generated by Django 2.2.14 on 2020-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song_img_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img_song',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
